In [1]:
import numpy as np
x=np.array([2,1,5,4,6,3])
np.sort(x)

array([1, 2, 3, 4, 5, 6])

In [4]:
i=np.argsort(x)
i

array([1, 0, 5, 3, 2, 4], dtype=int64)

In [5]:
rand=np.random.RandomState(42)
X=rand.randint(0,10,(4,6))
X

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [7]:
print(np.sort(X,axis=0))
print(np.sort(X,axis=1))
print(np.sort(X))

[[2 1 4 0 1 5]
 [5 2 5 4 3 7]
 [6 3 7 4 6 7]
 [7 6 7 4 9 9]]
[[3 4 6 6 7 9]
 [2 3 4 6 7 7]
 [1 2 4 5 7 7]
 [0 1 4 5 5 9]]
[[3 4 6 6 7 9]
 [2 3 4 6 7 7]
 [1 2 4 5 7 7]
 [0 1 4 5 5 9]]


In [10]:
x=np.array([9,11,3,1,6,20,4])
np.partition(x,3)


array([ 3,  1,  4,  6,  9, 20, 11])