In [14]:
import numpy as np
import matplotlib.pyplot as plt

In [15]:
name=['Alice','Bob','Cathy','Doug']
age=[25,45,17,19]
weight=[55,85,63,61]

In [16]:
data=np.zeros(4,dtype={'names':('name','age','weight'),
                       'formats':('U10','i4','f8')
                       })
data.dtype

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [17]:
data['name']=name
data['age']=age
data['weight']=weight
data

array([('Alice', 25, 55.), ('Bob', 45, 85.), ('Cathy', 17, 63.),
       ('Doug', 19, 61.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [18]:
print(data['name'])
print(data[1])  
print(data[-1]['name'])
print(data[data['age']<30]['name'])

['Alice' 'Bob' 'Cathy' 'Doug']
('Bob', 45, 85.)
Doug
['Alice' 'Cathy' 'Doug']


In [19]:
tp=np.dtype([('id','i8'),('mat','f8',(3,3))])
X=np.zeros(1,dtype = tp)
print(X[0])
print(X['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
print(data['age'])
data_rec=data.view(np.recarray)
print(data_rec.age)



[25 45 17 19]
[25 45 17 19]
